@startuml

'############################
' エンティティ
'############################
package インスタンス {
  entity サーバ {
    * リスナープロセス
    * サーバプロセス
    * SID
    --
    * プログラムグローバル領域
  }
    note top of サーバ
      SID：サーバ内の共有メモリ
      にアクセスする際に使用
    end note
  entity プログラムグローバル領域 {
    --
    * プライベートSQL領域
    * セッションメモリ
  }
  entity インスタンス {
    * グローバルデータベース名
    * サービス名
    * インスタンス名
    --
    * システムグローバル領域
    * バックグラウンドプロセス
  }
  note left of インスタンス
    インスタンス名：単一のインスタンスを識別
    サービス名：同じ機能を持つサービス名を識別
      （冗長構成時の仮想的な名前）
  end note
  entity システムグローバル領域 {

    * データベースバッファキャッシュ
    * REDOログバッファ
  }
  entity バックグラウンドプロセス
  entity DBWn
    note bottom
      データベースへの書き込み
    end note
  entity LGWR
    note bottom
      ログへの書き込み
    end note
}

package データベース {
  entity ストレージ装置 {
  }
  entity データベース {
    * 物理ファイル
  }
}

'############################
' リレーション
'############################
' layer1
ストレージ装置 }|-do-|{ データベース
サーバ }|-do-|{ インスタンス


' layer2
インスタンス }|-ri-|{ データベース
インスタンス o-do- システムグローバル領域
インスタンス o-do- バックグラウンドプロセス
サーバ o-le- プログラムグローバル領域

' layer3
システムグローバル領域 -ri- バックグラウンドプロセス
note on link #00ffff
  システムグローバル領域
  の内容を書き込み
end note
バックグラウンドプロセス <|-- DBWn
バックグラウンドプロセス <|-- LGWR

@enduml
