@startuml

' エンティティ
entity データベース {
}
entity スキーマ {
}
  note left of スキーマ
    MySQLでいうデータベース
    Oracleだと複数持つ
  end note
entity ユーザ {

}
entity データベースオブジェクト {
}
entity 表 {
  * インデックス
}
entity ビュー {
}
entity 順序 {
}
entity シノニム {
}
entity ストアドプログラム {
}

' 関係
データベース o-down- スキーマ
スキーマ o-down- データベースオブジェクト
スキーマ -right- ユーザ
  note on link
    スキーマごとに
    ユーザをもつ
  end note
データベースオブジェクト <|-down- 表
データベースオブジェクト <|-down- ビュー
データベースオブジェクト <|-down- 順序
データベースオブジェクト <|-down- シノニム
データベースオブジェクト <|-down- ストアドプログラム
ストアドプログラム <|-down- ストアドプロシージャ
ストアドプログラム <|-down- ストアドファンクション
ストアドプログラム <|-down- ストアドパッケージ
ストアドプログラム <|-down- データベーストリガー

@enduml